[package]
name = "pinball2d"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_rapier2d = "0.11"
bevy_prototype_lyon = "0.3.1"